name: buildAndDeploy

# 当master分支提交时
on:
  push:
    branches: 
      - master


# 开始任务
jobs:
  main:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    # 将代码拷贝到虚机中
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    # 安装和构建
    - name: Install and Build
      run: |
        echo "开始安装和构建"
        yarn
        yarn run build
        
    - name: Update dist folder to current repository
      run: |
        cd dist
        pwd
        ls
        git config --global user.email $EMAIL
        git config --global user.name $USER_NAME
        git config --global github.token $GITHUB_TOKEN
        git init
        git add -A
        git commit -m "GitHub Action 自动提交"
        git remote add origin https://github.com/$USER_NAME/$REPO_NAME.git
        git push --force --quiet origin master
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        USER_NAME: "0fengzi0"
        REPO_NAME: "Blog"
        EMAIL: "1209711408@qq.com"
