# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn run build
      
    - name: Commit files and push
      run: |
          cd dist
          git config --local user.email "bot@5ixf.vip"
          git config --local user.name "github bot"
          git add --all
          git commit -m "deploy `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
          git push -f https://GITHUB_TOKEN@github.com/0fengzi0/$dist_repo_name.git master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
